### ISSUE TITLE
UPnP-Device not shown a Airplay-Device

### ISSUE THREAD

**Issue by hismastersvoice** [philippe44/ShairTunes2#11]
Maybe not an issue...

When I setup a device via your UPnP Plugin the device will not be shown as a Air-Play-Device.
Is it possible to bring the function into your Plugin?

Thanks for your great work!

Dieter

**Comment by philippe44** [comment]
You have an option in the shairtunes2w plugin to allow all 'virtual' players to be used

**Comment by hismastersvoice** [comment]
Thanks.
I only have "Allow all Squeezelite-based Players".
Works this also for UPnP-Player?

**Comment by philippe44** [comment]
Yes, all my virtual players (upnp, chromecast, airplay) appear as squeezelite *based* players

**Comment by hismastersvoice** [comment]
Perfect... Thanks!

**Comment by philippe44** [comment]
Btw, if what you're really interested into is upnp to airplay bridge, look at my air connect solution. They are focusing on doing just that, outside of LMS and they are much better as shairtunes2w is pretty contorted. I recommend it for SB boxes, not for broader upnp (or chromecast)
