### ISSUE TITLE
Which firewall settings to be used for shairtunes2w?

### ISSUE THREAD

**Issue by Karlsoost** [philippe44/ShairTunes2#14]
Hi,

I managed to successfully install the plugin and it works like a charm without firewall. Great plugin!

Unfortunately I'm not able to configure my firewall successfully to allow the necessary traffic. Could you please determine which firewall rules to be applied?

I'm running the logitech media server on arch linux from the aur package https://aur.archlinux.org/packages/logitechmediaserver/ (logitechmediaserver 7.9.1.arch3-1) in combination with the ufw firewall. Everything is up-to-date.

For the logitech media server I have allowed port 9000 (tcp) and 3483 (tcp/udp) according to various logitech related sources. Additionally I'm allowing 5353 (udp) for the avahi service.

sudo ufw status
Status: active

To                         Action      From
--                         ------      ----
SSH                        ALLOW       Anywhere
22                         ALLOW       Anywhere
9000/tcp                   ALLOW       Anywhere
3483/tcp                   ALLOW       Anywhere
3483/udp                   ALLOW       Anywhere
5353/udp                   ALLOW       Anywhere
SSH (v6)                   ALLOW       Anywhere (v6)
22 (v6)                    ALLOW       Anywhere (v6)
9000/tcp (v6)              ALLOW       Anywhere (v6)
3483/tcp (v6)              ALLOW       Anywhere (v6)
3483/udp (v6)              ALLOW       Anywhere (v6)
5353/udp (v6)              ALLOW       Anywhere (v6)

What else needs to be opened?

Thanks for your advice.

Karlsoost

**Comment by philippe44** [comment]
It's dynamic ports that are opened so I can't tell in advance
