### ISSUE TITLE
Sound plays on wrong player!

### ISSUE THREAD

**Issue by larkery** [philippe44/ShairTunes2#16]
Hello,

This is great, but I have one weird problem which I'd appreciate a little help debugging, if you have any time. I have two squeeze clients in my house, one SB Touch and one squeezelite raspberry pi thing. I find with this plugin:

- If they are both powered on, I can use either one as an airplay output, but the sound always comes out of the squeezelite player. However the SB touch does show play information on its screen if you stream to it (even though sound goes elsewhere).
- If I turn off the squeezelite player, it plays back fine on the SB Touch.

Any ideas how to proceed? I can try and gather some logs or similar.

Thanks,

Tom

**Comment by larkery** [comment]
Oh, I should add:

I've tried un-checking player A (where the sound always comes out), and sending airplay to player B still plays on player A so long as player A is powered on. The only way to make sound come out of player B is to turn off player A.

One other thing which I will test when I have time is to disable the airplay output plugin which I am also using, in case the extra airplay speakers which I use as players are messing something up.

**Comment by philippe44** [comment]
Looks like a MAC confusion. Can you tell what's the address you've assigned to squeezelite? MAC is used by Shairtunes2W to broadcast the ID of the player to AirPlay controllers

**Comment by philippe44** [comment]
Closed for inactivity

**Comment by larkery** [comment]
Sorry, I forgot to write back which is quite rude. I never figured out the cause of the problem, but turning everything off and on again made it go away. Thank you for your time, and nice program!
