### ISSUE TITLE
Not an issue but feature request

### ISSUE THREAD

**Issue by simonrb2000** [philippe44/ShairTunes2#17]
Hi Philippe

Please delete this if its not feasible, when using Airplay to a device it works great! No issues whatsoever with syncing players - even AirPlay players that show as LMS players by your other plugin. 

Just a feature request, Sometimes its only one song you want to AirPlay or maybe you AirPlay an album then radios are off. When you come back to them later or next day for example the playlist is just a Shairtunes thing. Is there a way like you have in your Groups plugin to cache/save the playlist on a player and restore it once the connection has ended and the radio has turned off? 

Not sure its possible by hey, worth an ask :)

Thanks Philippe

**Comment by philippe44** [comment]
I can probably do that - ping me again in a couple of weeks

**Comment by simonrb2000** [comment]
Thanks mate!

**Comment by philippe44** [comment]
Have a look at the dev version and tell me if this is what you want. I don't have time for testing, so your feedback would be higly appreciated

**Comment by simonrb2000** [comment]
Just tried this on a couple of players and works perfectly.. Will try more intensively and using Group Players etc.. But initial results work. 

Just to clarify, as soon as you disconnect the AirPlay the player restores playlist then turns its self off - perfect!

**Comment by simonrb2000** [comment]
Ok, spent a few mins testing away and worked great! Only issue I ran into were with the volume but they are random and to do with something else. 

The restoring playlists is working fine, even AirPlaying to Group Players works. Something note, if a player is in a group, then AirPlay to that player when you are finished it will not restore it back to the group however will restore a playlist from before it was attached to the Group. This isn't an issue for me but worth mentioning.

Thanks again for your help Philippe44!

**Comment by philippe44** [comment]
The behaviour with group is by design. I've made the group feature to be as "frictionless" as possible so, for example, if a playlist is changed on a group member, the the assumption is that the user wants to extract that player from the group and play something else on it, but not affect the rest of the group 

That's also a key difference with classical sync group in LMS. In my groups, if you want to change what the group is playing, then you have to use the virtual player. The only exception to that rule is pause/prev/next, where I assume that you want to pause/prev/next the whole group when you pause/prev/next a member (that's a convenient to be able to press pause on any physical device). If you just want that device silent, then you can press power on it. 

Anyway, I'm digressing, but in the "combo" case you're describing, this is what's happening. ShairTunes2W indicates to the Group plugin that the device shall be removed from the group, so the Group plugin first restore the playlist before it joined the group. Then ShairTunes2 plays and when it stopped, it restores what was the playlist before it took over, i.e. the very intial playlist. All you have to do to have that player rejoining the Group is to stop/restart or next/prev the Group

**Comment by simonrb2000** [comment]
Thanks Philippe! The next/prev to get the player back in the group has never worked for me. I have to turn the player off and turn it on again to get a player back in the group. The restoring playlist after Airplaying is working great! Not found a fault with it and been toying with it all day.

**Comment by philippe44** [comment]
Sorry I was not clear. Once the player is out, it is out until you do something on the virtual player (or on one  member still part of the group). To be clearer, if you press next *while* a member is in the group, the whole group will go next. Once it's out, pressing next will be next on its "personal" playlist. But if you press next on another player, it shoudl re-join (although I have to double check, no that I'm writing that :-))

**Comment by simonrb2000** [comment]
Mine doesn't behave that way. To get the player back in the group, only pausing then resuming on the group player works. Players in the group don't do it. I assume this way works because it breaks up the group and then when you hit play it remakes the group then can grab the player that had previously been split from it

**Comment by simonrb2000** [comment]
What would be slick is when the player that has left the group gets turned off then it auto joins the virtual group it left if that virtual group is still there and playing. Then you can just power the player back on and its back in the group :D

**Comment by philippe44** [comment]
Yes, I re-checked my code and I only redo the group on play, not on next. I thought it was better like that b/c if somebody extract a member, it means 'I want to listen to this in my place, don't bother me again ..." so unless the "one higher authority of the house :-)" explicitely stop and Virtual Player and restart it, this other family member will have peace. Not perfect, but compromise
About your other proposal, the problem with that is, in the above scenario, when you power back on this player, it will play with the others, maybe not what you want int he room that was initially shut off

**Comment by simonrb2000** [comment]
I see. For my personal use, if the player leaves the group to play something, when its finished its then turned off. Its then finished with. If it joins the group again when turned off its back to where it started, in the group. Does that make sense? I think most people control players via AirPlay or iPeng so rather than turn the player on they just select radio they want and select what they want to play and the player powers on playing that song/album. So the turning on and it playing a song thats in the group us probably a rare case. Well thats how I use it, no doubt there are many people out there who do still physically turn a player on to select something to play using the players UI and screen. I can live with it the way it is, I'm very grateful for what you have done with this plugin and your others.

**Comment by philippe44** [comment]
I think i'll keep like that for now on, and will think about other changes later

**Comment by simonrb2000** [comment]
I respect that! 👍

**Comment by philippe44** [comment]
thanks
