### ISSUE TITLE
404 Not Found: plugins/Extensions/settings/plugins/ShairTunes2W/settings/basic.html

### ISSUE THREAD

**Issue by crmne** [philippe44/ShairTunes2#22]
Hi,

I'm running `Logitech Media Server Version: 7.9.2 - 1562753347 @ Wed Jul 10 12:48:25 CEST 2019` and `ShairTunes2 (fork) (v0.107.2)`.

Whenever I click on `Settings` I get this error:

    404 Not Found: plugins/Extensions/settings/plugins/ShairTunes2W/settings/basic.html

I tried to install it manually in `/var/lib/squeezeboxserver/Plugins` but it didn't change.

Any ideas?

**Comment by philippe44** [comment]
Can you post a server.log? Best is to discuss on the slimdevices forum

**Comment by philippe44** [comment]
Closed for inactivity

**Comment by jph76** [comment]
Bonjour, different user, same problem here.

This is the server log, beginning with LMS restart after plugin installation. Running on Debian 10.2.

`[20-02-07 07:56:39.5365] main::init (387) Starting Logitech Media Server (v7.9.2, 1578996832, Tue Jan 14 12:15:02 CET 2020) perl 5.024001 - x86_64-linux-gnu-thread-multi
[20-02-07 07:56:42.6001] Slim::Web::Cometd::handler (421) errorNeedsClient: 00:04:20:28:83:6c, status, -, 10, menu:menu, useContextMenu:1, subscribe:600
[20-02-07 07:56:43.1297] Slim::Web::Cometd::handler (421) errorNeedsClient: 00:04:20:2a:1e:66, status, -, 10, menu:menu, useContextMenu:1, subscribe:600
[20-02-07 07:56:59.8660] Slim::Formats::RemoteStream::open (105) Can't open socket to [wdr-edge-2020-fra-lg-cdn.cast.addradio.de:443]: 22: Invalid argument
[20-02-07 07:56:59.8665] Slim::Player::Song::open (471) Warning: stream failed to open [https://addrad.io/4WRNCS].`

**Comment by jph76** [comment]
Found a solution while googling the web: for Debian, install libcrypt-openssl-rsa-perl and restart LMS. I’m posting this here for other people looking at this issue.

The package may have a slightly different name on other distros.

**Comment by Phil-Friderici** [comment]
Had the same issue on CentOS 7.8.2003. The package name here is perl-Crypt-OpenSSL-RSA. Install the package and restart LMS did the trick :)

`yum install perl-Crypt-OpenSSL-RSA`

**Comment by hartzell** [comment]
I had the same problem in a Free{NAS,BSD} jail running perl5.30 and `Logitech Media Server Version: 7.9.2 - TRUNK @ UNKNOWN`.

Fixed with `pkg install p5-Crypt-OpenSSL-RSA`.

**Comment by philippe44** [comment]
Yes, I need to build perl 5.30 libraries ...

**Comment by hartzell** [comment]
@philippe44 -- I hope you didn't take my note as grumpy, just trying to leave helpful breadcrumps.  

I *love* having the plugin working!

**Comment by migmedia** [comment]
@philippe44  Can you please provide perl 5.32 libraries? I am running LMS 8.1.2  on Freenas  with perl 5.32

**Comment by philippe44** [comment]
Try 0.205.0

**Comment by schmurtzm** [comment]
Same issue on Ubuntu 20.04.3 LTS, thanks @jph76  it works again ;) 
```
sudo apt-get update
sudo apt-get install libcrypt-openssl-rsa-perl
```
