### ISSUE TITLE
Players stop being published after a couple of minutes

### ISSUE THREAD

**Issue by soberdor** [philippe44/ShairTunes2#27]
This behaviour came up just a couple of weeks ago (latest LMS on Windows 10 with 3 squeezeboxes). After a fresh reboot the squeezeboxes will be discovered on iOS devices, however only for some minutes. If during that time playback is started, it will continue to work. If I "re-publish" in the LMS settings interface, the players appear again, again only for some minutes.

[shairtunes2-00-04-20-17-3a-9d.log](https://github.com/philippe44/ShairTunes2/files/4515860/shairtunes2-00-04-20-17-3a-9d.log)

**Comment by philippe44** [comment]
Look for IGMP snooping in your router setting

**Comment by soberdor** [comment]
Thanks! I found the setting and enabled it (ubiquiti/unifi system), but unfortunately the behaviour is still the same.
