### ISSUE TITLE
In LMS: encoding parameters select no text

### ISSUE THREAD

**Issue by marrem** [philippe44/ShairTunes2#29]
![afbeelding](https://user-images.githubusercontent.com/2941173/82490726-f8c2ef80-9ae3-11ea-80aa-5675d7392ace.png)

Installed shairtunes2 on LMS 8 (Arm (raspbian)). I can't see text in encoding params selector.

![afbeelding](https://user-images.githubusercontent.com/2941173/82490958-4b041080-9ae4-11ea-8870-590b016c9276.png)

**Comment by marrem** [comment]
When I do choose flac (second from bottom) I do get sound. When I restart lms it goes back to wav.  Second from top. Also the settings file is written with 
`codec: wav` overwriting the `codec: flc:4` setting I choose earlier.

**Comment by philippe44** [comment]
Have you tried another browser?

**Comment by marrem** [comment]
I have now. The previous one (where it didn't show the labels was Firefox 76.0.1 Mac).
On Safari (13.1) it does show: 
![Schermafbeelding 2020-05-25 om 23 09 24](https://user-images.githubusercontent.com/2941173/82843295-0a8a0580-9edd-11ea-893f-580820ab7e7c.png)
![Schermafbeelding 2020-05-25 om 23 02 15](https://user-images.githubusercontent.com/2941173/82843296-0b229c00-9edd-11ea-825f-7a375f0daf7f.png)
![Schermafbeelding 2020-05-25 om 23 02 07](https://user-images.githubusercontent.com/2941173/82843297-0bbb3280-9edd-11ea-9fdf-22dd1ac23496.png)

... on both _standard_ and _material_ skin.

And on Chrome ( 81.0.4044.138 Mac) it does too.

Though I wonder what the (still) empty one on top is.



So that part has been solved.

But that leaves me with the more annoying problem that whenever I set the encoding to something other than _wave_ and then restart the server (systemctl restart ...) it goes back to _wave_ again. It just overwrites `/var/lib/squeezeboxserver/prefs/plugin/shairtunes.prefs` and puts back the line `codec: wav`

**Comment by philippe44** [comment]
The empty 1st line is to let you set the default (plugin choses). Now, I have no idea why you're getting back to 'wav' at startup. Can you try to erase the prefs file? Because if you look at plugin's code, it sets to 'flc' when there is nothing, never to 'wav'

**Comment by philippe44** [comment]
Closed for inactivity
