### ISSUE TITLE
Automatic start after Raspberry Pi reboot

### ISSUE THREAD

**Issue by MariuszT** [philippe44/ShairTunes2#34]
The plugin works great, but I have a problem with its automatic start. After rebooting my Raspberry Pi there are no players available. I just have to click Re-publish button manually and then everything works fine again. Until the next reboot. Is there any way to make it work automatically? And if not, maybe I could do it somehow with CLI instead of manually work?

**Comment by philippe44** [comment]
It should restart with LMS. If it does not, it means there is an issue with the boot sequence of your system
