### ISSUE TITLE
Is it possible to limit the port range being used by the helper program?

### ISSUE THREAD

**Issue by hansherlighed** [philippe44/ShairTunes2#35]
Hi,

I'm trying to run your plugin in the "official/community" docker LMS image, and I'm not able to get it working without sing the HOST network option for the container. I'd rather not use the HOST network in my container.
From what i can gather, the issue with running your plugin in docker is that the helper program assigns dynamic port numbers for each of the squeezebox devices, and therefore it is not possible to setup the correct port forwarding/publishing in docker. Is it possible to:
1: know what the range of port numbers re being used by the plugin
2: somehow limit the port range? I only have 4 devices, so a port range of 10-20 ports should be enough.

Thanks.

**Comment by philippe44** [comment]
No, ports are fully dynamic

**Comment by cbueche** [comment]
Hi, same issue for me, see [my forum post](https://forums.slimdevices.com/showthread.php?106289-announce-ShairTunes2W-Airtunes-on-LMS-(forked-version-with-Windows-support)&p=996586&viewfull=1#post996586).

**Comment by philippe44** [comment]
Ports can now be set

**Comment by lorenzoferrarajr** [comment]
Thank you @philippe44, can you describe how to use the `Inbound ports` option? The description states:

>  AirPlay protocol requires three incoming ports and the built-in webserver needs another one. Set the base value and count (don't forget to open these in your firewall). Leave empty for automatic selection

Questions:

- How do I choose the 3 ports? It looks like I can only set one "base" port.
- What's the `count` parameter for?

Thank you!

**Comment by philippe44** [comment]
Each player requires one port when it is just listening for possible incoming connection and when it is playing it requires 3 extra ports. So you chose one "base" port that is available in your system (really, your choice, use netstat maybe to get some help) and then you tell the helper that it can use up to "count" ports from that base. It will decide automatically select available ports is that range: "base ... base+count". 
The base and count parameter are shared accross all players, so if you have 4 SB devices that you want to be used at the same time by AirPaly, then you need at least 4*4=16 ports. Don't be cheap then, allow 32 :-)

**Comment by lorenzoferrarajr** [comment]
Great explanation, thank you!
