### ISSUE TITLE
Plugin is working, but no sound comes out

### ISSUE THREAD

**Issue by TroLoos** [philippe44/ShairTunes2#38]
Dear All,

I'm moving my LMS server from Docker to LXC container, so that I have a little bit more control over it - with Docker I've been having issues from time to time, like recently my LMS died and stopped responding because of ShairTunes2 plugin (didn't update anything, really out of no apparent reason).

It's a LXC container with Debian 10.7 CT template.

Everything's almost already done with plugins I use, except for ShairTunes2. I've had to install additional package: libcrypt-openssl-rsa-perl, and it started ok, looking like it's working but no sound is coming out of speakers (tried several different players as well). Players in GUI look like playing at first, but then they stop.

What am I missing? I'm sure it's some important package but can't really figure out which one...

server.log: https://pastebin.com/19tzdvw4
shairtunes.log: https://pastebin.com/maqQby7c

**Comment by philippe44** [comment]
What Perl version do you have? Is your docker in host mode?

**Comment by TroLoos** [comment]
> What Perl version do you have? Is your docker in host mode?

Well, your question got me thinking, and it turns out it was my fault. I'm not using Docker for LMS, only LXC container on Proxmox (a bit closer to physical resources than Docker).

It didn't work because my LXC had 2 network interfaces, one that was connected to main network, and second one that was a separate VLAN. It seems like it tried to stream from the latter, and it didn't work. I fixed it by removing 2nd interface and now it works fine as expected.

Thank you philippe44 for your great work with this plugin and all other that you created and I'm using every day :-).

**Comment by philippe44** [comment]
Thanks
