### ISSUE TITLE
AirPlay Connection is working only 1 time

### ISSUE THREAD

**Issue by bobbythemoh** [philippe44/ShairTunes2#39]
Hi, i am using ShairTunes2 (fork) (0.205.1) on Logitech Media Server 8.3.0~1635199649 with Squeezelite Player 1.9.9-1391. Selecting a Zone on an iPhone (iOs 15.0.2) connets and plays the content without any issue. After disconnecting from the Zone reconnecting is not possible any more (iPhone keeps spinning and tells after approx. 30 Seconds that the connnection is not possible). Klicking "Wipe" in the LMS settings enables the connection immediately again, but after disconnecting the situation repeats.
So to get the Plugin working i need to "Wipe" after every single stream. Can you tell what I should look for or what i am doing wrong? Please find below my settings:

<img width="597" alt="Screenshot 2021-10-26 105432" src="https://user-images.githubusercontent.com/38766001/138846192-5f84e49f-9176-4c73-87e5-e5a06730a37b.png">

Looking forward for your reply, thank you in advance

**Comment by philippe44** [comment]
It would be easier to discuss on the LMS forums. I will need a log anyway

**Comment by bobbythemoh** [comment]
Hi OK, i posted some details here, thank you in advance.
[LINK](https://forums.slimdevices.com/showthread.php?106289-announce-ShairTunes2W-Airtunes-on-LMS-(forked-version-with-Windows-support)&p=1038745&viewfull=1#post1038745)
