### ISSUE TITLE
Not working with SB Duet/Receiver 

### ISSUE THREAD

**Issue by hindsholm** [philippe44/ShairTunes2#9]
First of all, let me say that this is an amazing plugin! It works brilliantly with my SB Radio - sound, cover art etc. is perfect.

But I normally use one of my three SB Receivers, and they don't work at all. I don't see anything suspicious in the LMS server log, but instead of music, I only hear a short loud "scratch" sound every once in a while.

I suspect this has to do with the fact that the SB Receiver does not support the same codecs as the Radio, but I am not even sure which audio format I am dealing with - the information in the LMS UI just says "WAV".

I hope you will be able to cast some light on this...

PS: I intended to post a message on forums.slimdevices.com but even though I registered as a user, I don't have posting rights.

**Comment by philippe44** [comment]
It works on my configuration; LSM 7.7.6 on Windows and a duet, playing from any source. Can you tell more about your config?

**Comment by hindsholm** [comment]
I'm closing this issue because it is also being discussed on [forums.slimdevices.com](http://forums.slimdevices.com/showthread.php?106289-announce-ShairTunes2W-Airtunes-on-LMS-(forked-version-with-Windows-support)&p=872936&viewfull=1#post872936).
